# Generated by Django 5.2 on 2025-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_code',
            field=models.CharField(choices=[('F', 'Flowers'), ('B', 'Bouqets'), ('T', 'Toys')], default='B', max_length=1),
        ),
    ]
