# Generated by Django 5.2 on 2025-04-23 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category_product_category_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_code',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('F', 'Flowers'), ('B', 'Bouquets'), ('T', 'Toys')], default='B', max_length=100),
        ),
    ]
